### ISSUE TITLE
ssh key handling

### ISSUE THREAD

**Issue by stefhen** [stefhen/migrate-deployments#9]
``` bash

? 0
/Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:361:in `block (2 levels) in do_get': Error: HTTP Code: 422, Response body: ResourceNotFound: ActiveRecord::RecordNotFound (RightApi::ApiError)
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
        from /Users/stefhenhovland/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:111:in `follow_redirection'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:357:in `block (2 levels) in do_get'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
        from /Users/stefhenhovland/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:339:in `block in do_get'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:218:in `retry_request'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:337:in `do_get'
        from /Users/stefhenhovland/work/stuff/rsc/migration-steps/.gems/gems/right_api_client-1.5.26/lib/right_api_client/client.rb:196:in `resource'
        from ./copy-deployment.rb:209:in `find_ssh_key'
        from ./copy-deployment.rb:147:in `block in create_servers'
        from ./copy-deployment.rb:138:in `each'
        from ./copy-deployment.rb:138:in `create_servers'
        from ./copy-deployment.rb:34:in `main'
        from ./copy-deployment.rb:319:in `<main>'
```

**Comment by stefhen** [comment]
Fix in #11
